using AccountService.Domain.Entities;
using AccountService.Infrastructure.Persistence.ReadModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AccountService.Infrastructure.Persistence.Configurations;

/// <summary>
/// Fluent mapping of the Cuenta entity: natural PK (no identity), enum stored
/// as text and FK to the ClientesLectura read model. Matches database.sql.
/// </summary>
public sealed class CuentaConfiguration : IEntityTypeConfiguration<Cuenta>
{
    public void Configure(EntityTypeBuilder<Cuenta> builder)
    {
        builder.ToTable("Cuentas");

        // Natural business key assigned by the bank: NOT generated by the DB.
        builder.HasKey(c => c.NumeroCuenta);
        builder.Property(c => c.NumeroCuenta).ValueGeneratedNever();

        builder.Property(c => c.TipoCuenta)
            .HasConversion<string>()
            .HasMaxLength(50);

        builder.Property(c => c.SaldoInicial).HasPrecision(18, 2);
        builder.Property(c => c.Estado).IsRequired();
        builder.Property(c => c.ClienteId).IsRequired();

        builder.HasOne<ClientesLectura>()
            .WithMany()
            .HasForeignKey(c => c.ClienteId)
            .HasConstraintName("FK_Cuentas_ClientesLectura");
    }
}